Import('OS_ROOT')
Import('osconfig')
from build_tools import *

src = []
CPPDEFINES = []

pwd = PresentDir()

if IsDefined(['OS_USING_PIN', 'BSP_USING_GPIO']):
    src += ['drv_gpio.c']

if  IsDefined(['OS_USING_SERIAL', 'BSP_USING_LPUART']):
    src += ['drv_uart.c']

if  IsDefined(['OS_USING_CLOCKEVENT', 'BSP_USING_GPT']):
    src += ['drv_hwtimer.c']

if IsDefined(['OS_USING_RTC', 'BSP_USING_RTC']) or IsDefined(['OS_USING_RTC', 'BSP_USING_RTC_LP']):
    src += ['drv_rtc.c']

if  IsDefined(['OS_USING_SPI', 'BSP_USING_LPSPI']):
    src += ['drv_spi.c']

if IsDefined('OS_USING_SDIO_NXP'):
    src += ['drv_sdio_common.c']
    
if IsDefined('OS_SDIO_DEVICE_SDIO'):
    src += ['drv_sdio.c']
    
if IsDefined('OS_SDIO_DEVICE_SD'):
    src += ['drv_sd.c']

if IsDefined('OS_SDIO_DEVICE_MMC'):
    src += ['drv_mmc.c']
    
if  IsDefined(['OS_USING_I2C', 'BSP_USING_LPI2C']):
    src += ['drv_i2c.c']

if IsDefined(['OS_USING_WDG', 'BSP_USING_WDOG']) or IsDefined(['OS_USING_WDG', 'BSP_USING_RTWDOG']):
    src += ['drv_wdg.c']

if IsDefined('OS_USING_PWM'):
    src += ['drv_pwm.c']

if IsDefined(['OS_USING_ADC', 'BSP_USING_ADC']):
    src += ['drv_adc.c']

if IsDefined(['OS_USING_CAN', 'BSP_USING_CAN']):
    src += ['drv_can.c']
    
if IsDefined('BSP_USING_SDRAM'):
    src += ['drv_sdram.c']

if IsDefined(['OS_USING_GRAPHIC', 'BSP_USING_LCD']):
    src += ['drv_lcd.c']

if IsDefined(['NET_USING_LWIP', 'BSP_USING_ETH']):
    src += ['drv_eth.c']
    
if IsDefined(['OS_USING_SAI', 'BSP_USING_SAI']):
    src += ['drv_sai.c']
    
if IsDefined(['OS_USING_HWCRYPTO', 'BSP_USING_TRNG']):
    src += ['drv_rng.c']    

if IsDefined(['OS_USING_USB_DEVICE', 'BSP_USING_USB_DEVICE']):
    src += ['drv_usbd.c']
    
#if IsDefined('OS_USING_FAL'):
#    src += [pwd+'/norflash/fal_drv_flash.c']
    
src += ['drv_common.c']

path =  [pwd]
path += [pwd + '/norflash']

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_NXP_IMXRT'], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')
