Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_PIN']):
    src += ['drv_gpio.c']
 
if IsDefined(['OS_USING_SERIAL']):
    src += ['drv_uart.c']
    
if IsDefined(['OS_USING_RTC']):
    src += ['drv_rtc.c']

if IsDefined(['OS_USING_SDIO_MM32']):
    src += ['drv_sdio.c']
    
path =  [pwd]

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_MM32F327XX'], CPPPATH = path)

Return('group')
