#ifndef __ONEOS_CONFIG_H__
#define __ONEOS_CONFIG_H__

#define BOARD_CMCC_ONEOS
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M4

/* Kernel */

#define OS_CUSTOMIZED_CONFIG
#define OS_NAME_MAX 15
#define OS_TASK_PRIORITY_MAX 32
#define OS_MAIN_TASK_STACK_SIZE 2048
#define OS_IDLE_TASK_STACK_SIZE 256
#define OS_RECYCLE_TASK_STACK_SIZE 256
#define OS_USING_TIMER
#define OS_TIMER_TASK_STACK_SIZE 512
#define OS_USING_MUTEX
#define OS_USING_SEMAPHORE
#define OS_USING_EVENT
#define OS_USING_MESSAGEQUEUE
#define OS_USING_MAILBOX
#define OS_USING_SYS_HEAP
#define OS_USING_MEM_HEAP
#define OS_USING_ALG_SMALL
#define OS_MEM_ALGORITHM_MINIMIZATION
#define OS_DEBUG
#define EXCEPTION_SIMPLE_HANDLE
#define OS_TICK_PER_SECOND 100
#define OS_SCHEDULE_TIME_SLICE 10

/* Task */

#define OS_NAME_MAX_15
#define OS_TASK_PRIORITY_32
/* end of Task */

/* Timer */

/* end of Timer */

/* IPC */

/* end of IPC */

/* Memory */

/* algorithm */

#define OS_USING_ALG_FIRSTFIT
/* end of algorithm */
#define OS_USING_MEM_POOL
/* end of Memory */

/* Debug */

#define OS_USING_ASSERT
#define OS_USING_KERNEL_LOCK_CHECK
#define OS_USING_KERNEL_DEBUG
#define KLOG_GLOBAL_LEVEL_WARNING
#define KLOG_GLOBAL_LEVEL 1
#define KLOG_USING_COLOR
#define KLOG_WITH_FUNC_LINE
#define OS_USING_OVERFLOW_CHECK
/* end of Debug */
/* end of Kernel */

/* Drivers */

/* Device */

#define OS_USING_DEVICE
#define OS_DEVICE_NAME_MAX 15
/* end of Device */
#define OS_USING_FAL

/* Console */

#define OS_USING_CONSOLE
#define OS_CONSOLE_DEVICE_NAME "uart3"
#define OS_LOG_BUFF_SIZE 256
/* end of Console */

/* Serial */

#define OS_USING_SERIAL
#define OS_SERIAL_IDLE_TIMER
#define OS_SERIAL_RX_BUFSZ 64
#define OS_SERIAL_TX_BUFSZ 64
/* end of Serial */

/* Timer */

#define OS_USING_TIMER_DRIVER
#define OS_USING_CLOCKSOURCE
#define OS_USING_CLOCKEVENT
#define OS_USING_HRTIMER
#define OS_USING_HRTIMER_FOR_KERNEL_TICK

/* cortex-m hardware timer config */

#define OS_USING_SYSTICK_FOR_CLOCKSOURCE
/* end of cortex-m hardware timer config */
/* end of Timer */

/* LPMGR */

/* end of LPMGR */
#define OS_USING_PUSH_BUTTON
#define OS_USING_LED

/* ADC */

/* end of ADC */
#define OS_USING_PIN
#define OS_PIN_MAX_CHIP 1

/* HAL */

#define MANUFACTOR_STM32
#define SERIES_STM32L4
#define SOC_STM32L475VG

/* Configure base hal in STM32CubeMX */

/* end of HAL */

/* RTC */

/* end of RTC */
/* end of Drivers */

/* Components */

/* Atest */

#define OS_USING_ATEST
#define ATEST_TASK_STACK_SIZE 1024
#define ATEST_TASK_PRIORITY 20
/* end of Atest */

/* Dlog */

#define OS_USING_DLOG
#define DLOG_PRINT_LVL_I
#define DLOG_GLOBAL_PRINT_LEVEL 6
#define DLOG_COMPILE_LVL_D
#define DLOG_COMPILE_LEVEL 7
#define DLOG_USING_ISR_LOG
#define DLOG_USING_FILTER
#define DLOG_USING_ASYNC_OUTPUT
#define DLOG_ASYNC_OUTPUT_BUF_SIZE 2048
#define DLOG_ASYNC_OUTPUT_TASK_STACK_SIZE 2048
#define DLOG_ASYNC_OUTPUT_TASK_PRIORITY 20
#define DLOG_USING_SYSLOG

/* Log format */

#define DLOG_WITH_FUNC_LINE
#define DLOG_USING_COLOR
#define DLOG_OUTPUT_TIME_INFO
/* end of Log format */

/* Dlog backend option */

#define DLOG_BACKEND_USING_CONSOLE
/* end of Dlog backend option */
/* end of Dlog */
#define OS_USING_NEWLIB_ADAPTER
#define OS_USING_ARMCCLIB_ADAPTER
#define OS_USING_LIBC_ADAPTER

/* Molink */

#define NET_USING_MOLINK
#define MOLINK_USING_GENERAL_OPS
#define MOLINK_USING_NETSERV_OPS
#define MOLINK_USING_PING_OPS
#define MOLINK_USING_NETCONN_OPS
#define MOLINK_USING_TCP
#define MOLINK_USING_UDP
#define MOLINK_USING_SELECT
#define MOLINK_USING_DNS
#define MOLINK_USING_ADDRINFO
#define MOLINK_USING_SOCKETS_OPS
#define MOLINK_USING_ONENET_NB_OPS
#define MOLINK_USING_WIFI_OPS
#define MOLINK_USING_IP
#define MOLINK_USING_IPV4
#define MOLINK_PLATFORM_MCU
#define MOLINK_USING_MO_LIB
#define MOLINK_USING_MO_TIME

/* Easylog */

/* end of Easylog */

/* Modules */

#define MOLINK_USING_EC200X_600S
#define MOLINK_USING_ML302
#define MOLINK_USING_GM190
#define MOLINK_USING_A7600X
#define MOLINK_USING_A7670X
#define MOLINK_USING_L610
#define MOLINK_USING_AIR723UG
#define MOLINK_USING_N58
#define MOLINK_USING_CLM920RV3
#define MOLINK_USING_AIR720UH
#define MOLINK_USING_GM510
#define MOLINK_USING_EC20
#define MOLINK_USING_SIM7600CE
#define MOLINK_USING_ME3630_W
#define MOLINK_USING_M5310A
#define MOLINK_USING_M5311
#define MOLINK_USING_BC95
#define MOLINK_USING_BC28
#define MOLINK_USING_BC26
#define MOLINK_USING_BC20
#define MOLINK_USING_SIM7020
#define MOLINK_USING_SIM7070X
#define MOLINK_USING_N21
#define MOLINK_USING_GM120
#define MOLINK_USING_ME3616
#define MOLINK_USING_ESP8266
#define MOLINK_USING_ESP32
#define MOLINK_USING_MULTI_MODULES
#define EC200X_600S_USING_GENERAL_OPS
#define EC200X_600S_USING_NETSERV_OPS
#define EC200X_600S_USING_NETCONN_OPS
#define EC200X_600S_USING_TCP
#define EC200X_600S_USING_UDP
#define EC200X_600S_USING_SELECT
#define EC200X_600S_USING_DNS
#define EC200X_600S_USING_ADDRINFO
#define EC200X_600S_USING_SOCKETS_OPS
#define ML302_USING_GENERAL_OPS
#define ML302_USING_NETSERV_OPS
#define ML302_USING_NETCONN_OPS
#define ML302_USING_TCP
#define ML302_USING_UDP
#define ML302_USING_SELECT
#define ML302_USING_DNS
#define ML302_USING_ADDRINFO
#define ML302_USING_SOCKETS_OPS
#define GM190_USING_GENERAL_OPS
#define GM190_USING_NETSERV_OPS
#define GM190_USING_NETCONN_OPS
#define GM190_USING_TCP
#define GM190_USING_UDP
#define GM190_USING_SELECT
#define GM190_USING_DNS
#define GM190_USING_ADDRINFO
#define GM190_USING_SOCKETS_OPS
#define A7600X_USING_GENERAL_OPS
#define A7600X_USING_NETSERV_OPS
#define A7600X_USING_NETCONN_OPS
#define A7600X_USING_TCP
#define A7600X_USING_UDP
#define A7600X_USING_SELECT
#define A7600X_USING_DNS
#define A7600X_USING_ADDRINFO
#define A7600X_USING_SOCKETS_OPS
#define A7670X_USING_GENERAL_OPS
#define A7670X_USING_NETSERV_OPS
#define A7670X_USING_NETCONN_OPS
#define A7670X_USING_TCP
#define A7670X_USING_UDP
#define A7670X_USING_SELECT
#define A7670X_USING_DNS
#define A7670X_USING_ADDRINFO
#define A7670X_USING_SOCKETS_OPS
#define L610_USING_GENERAL_OPS
#define L610_USING_NETSERV_OPS
#define L610_USING_NETCONN_OPS
#define L610_USING_TCP
#define L610_USING_UDP
#define L610_USING_SELECT
#define L610_USING_DNS
#define L610_USING_ADDRINFO
#define L610_USING_SOCKETS_OPS
#define AIR723UG_USING_GENERAL_OPS
#define AIR723UG_USING_NETSERV_OPS
#define AIR723UG_USING_NETCONN_OPS
#define AIR723UG_USING_TCP
#define AIR723UG_USING_UDP
#define AIR723UG_USING_SELECT
#define AIR723UG_USING_DNS
#define AIR723UG_USING_ADDRINFO
#define AIR723UG_USING_SOCKETS_OPS
#define N58_USING_GENERAL_OPS
#define N58_USING_NETSERV_OPS
#define N58_USING_NETCONN_OPS
#define N58_USING_TCP
#define N58_USING_UDP
#define N58_USING_SELECT
#define N58_USING_DNS
#define N58_USING_ADDRINFO
#define N58_USING_SOCKETS_OPS
#define CLM920RV3_USING_GENERAL_OPS
#define CLM920RV3_USING_NETSERV_OPS
#define CLM920RV3_USING_PING_OPS
#define CLM920RV3_USING_NETCONN_OPS
#define CLM920RV3_USING_TCP
#define CLM920RV3_USING_UDP
#define CLM920RV3_USING_SELECT
#define CLM920RV3_USING_DNS
#define CLM920RV3_USING_ADDRINFO
#define CLM920RV3_USING_SOCKETS_OPS
#define AIR720UH_USING_GENERAL_OPS
#define AIR720UH_USING_NETSERV_OPS
#define AIR720UH_USING_NETCONN_OPS
#define AIR720UH_USING_TCP
#define AIR720UH_USING_UDP
#define AIR720UH_USING_SELECT
#define AIR720UH_USING_DNS
#define AIR720UH_USING_ADDRINFO
#define AIR720UH_USING_SOCKETS_OPS
#define GM510_USING_GENERAL_OPS
#define GM510_USING_NETSERV_OPS
#define GM510_USING_NETCONN_OPS
#define GM510_USING_TCP
#define GM510_USING_UDP
#define GM510_USING_SELECT
#define GM510_USING_DNS
#define GM510_USING_ADDRINFO
#define GM510_USING_SOCKETS_OPS
#define EC20_USING_GENERAL_OPS
#define EC20_USING_NETSERV_OPS
#define EC20_USING_NETCONN_OPS
#define EC20_USING_TCP
#define EC20_USING_UDP
#define EC20_USING_SELECT
#define EC20_USING_DNS
#define EC20_USING_ADDRINFO
#define EC20_USING_SOCKETS_OPS
#define SIM7600CE_USING_GENERAL_OPS
#define SIM7600CE_USING_NETSERV_OPS
#define SIM7600CE_USING_NETCONN_OPS
#define SIM7600CE_USING_TCP
#define SIM7600CE_USING_UDP
#define SIM7600CE_USING_SELECT
#define SIM7600CE_USING_DNS
#define SIM7600CE_USING_ADDRINFO
#define SIM7600CE_USING_SOCKETS_OPS
#define ME3630_W_USING_GENERAL_OPS
#define ME3630_W_USING_NETSERV_OPS
#define ME3630_W_USING_NETCONN_OPS
#define ME3630_W_USING_TCP
#define ME3630_W_USING_UDP
#define ME3630_W_USING_SELECT
#define ME3630_W_USING_DNS
#define ME3630_W_USING_ADDRINFO
#define ME3630_W_USING_SOCKETS_OPS
#define M5310A_USING_GENERAL_OPS
#define M5310A_USING_NETSERV_OPS
#define M5310A_USING_NETCONN_OPS
#define M5310A_USING_TCP
#define M5310A_USING_UDP
#define M5310A_USING_SELECT
#define M5310A_USING_DNS
#define M5310A_USING_ADDRINFO
#define M5310_USING_SOCKETS_OPS
#define M5311_USING_GENERAL_OPS
#define M5311_USING_NETSERV_OPS
#define M5311_USING_NETCONN_OPS
#define M5311_USING_TCP
#define M5311_USING_UDP
#define M5311_USING_SELECT
#define M5311_USING_DNS
#define M5311_USING_ADDRINFO
#define M5311_USING_SOCKETS_OPS
#define M5311_USING_ONENET_NB_OPS
#define BC95_USING_GENERAL_OPS
#define BC95_USING_NETSERV_OPS
#define BC95_USING_NETCONN_OPS
#define BC95_USING_TCP
#define BC95_USING_UDP
#define BC95_USING_SELECT
#define BC95_USING_DNS
#define BC95_USING_ADDRINFO
#define BC95_USING_SOCKETS_OPS
#define BC28_USING_GENERAL_OPS
#define BC28_USING_NETSERV_OPS
#define BC28_USING_NETCONN_OPS
#define BC28_USING_TCP
#define BC28_USING_UDP
#define BC28_USING_SELECT
#define BC28_USING_DNS
#define BC28_USING_ADDRINFO
#define BC28_USING_SOCKETS_OPS
#define BC26_USING_GENERAL_OPS
#define BC26_USING_NETSERV_OPS
#define BC26_USING_NETCONN_OPS
#define BC26_USING_TCP
#define BC26_USING_UDP
#define BC26_USING_SELECT
#define BC26_USING_DNS
#define BC26_USING_ADDRINFO
#define BC26_USING_SOCKETS_OPS
#define BC20_USING_GENERAL_OPS
#define BC20_USING_NETSERV_OPS
#define BC20_USING_NETCONN_OPS
#define BC20_USING_TCP
#define BC20_USING_UDP
#define BC20_USING_SELECT
#define BC20_USING_DNS
#define BC20_USING_ADDRINFO
#define BC20_USING_SOCKETS_OPS
#define SIM7020_USING_GENERAL_OPS
#define SIM7020_USING_NETSERV_OPS
#define SIM7020_USING_NETCONN_OPS
#define SIM7020_USING_TCP
#define SIM7020_USING_UDP
#define SIM7020_USING_SELECT
#define SIM7020_USING_DNS
#define SIM7020_USING_ADDRINFO
#define SIM7020_USING_SOCKETS_OPS
#define SIM7070X_USING_GENERAL_OPS
#define SIM7070X_USING_NETSERV_OPS
#define SIM7070X_USING_NETCONN_OPS
#define SIM7070X_USING_TCP
#define SIM7070X_USING_UDP
#define SIM7070X_USING_SELECT
#define SIM7070X_USING_DNS
#define SIM7070X_USING_ADDRINFO
#define SIM7070X_USING_SOCKETS_OPS
#define N21_USING_GENERAL_OPS
#define N21_USING_NETSERV_OPS
#define N21_USING_NETCONN_OPS
#define N21_USING_TCP
#define N21_USING_UDP
#define N21_USING_SELECT
#define N21_USING_DNS
#define N21_USING_ADDRINFO
#define N21_USING_SOCKETS_OPS
#define GM120_USING_GENERAL_OPS
#define GM120_USING_NETSERV_OPS
#define GM120_USING_NETCONN_OPS
#define GM120_USING_TCP
#define GM120_USING_UDP
#define GM120_USING_SELECT
#define GM120_USING_DNS
#define GM120_USING_ADDRINFO
#define GM120_USING_SOCKETS_OPS
#define ME3616_USING_GENERAL_OPS
#define ME3616_USING_NETSERV_OPS
#define ME3616_USING_NETCONN_OPS
#define ME3616_USING_TCP
#define ME3616_USING_UDP
#define ME3616_USING_SELECT
#define ME3616_USING_DNS
#define ME3616_USING_ADDRINFO
#define ME3616_USING_SOCKETS_OPS
#define ESP8266_CONNECT_SSID "ssid"
#define ESP8266_CONNECT_PASSWORD "password"
#define ESP8266_USING_GENERAL_OPS
#define ESP8266_USING_WIFI_OPS
#define ESP8266_USING_NETCONN_OPS
#define ESP8266_USING_TCP
#define ESP8266_USING_UDP
#define ESP8266_USING_SELECT
#define ESP8266_USING_DNS
#define ESP8266_USING_ADDRINFO
#define ESP8266_USING_SOCKETS_OPS
#define ESP8266_USING_HW_CONTROL
#define ESP8266_RST_PIN_NUM -1
#define ESP32_CONNECT_SSID "ssid"
#define ESP32_CONNECT_PASSWORD "password"
#define ESP32_USING_GENERAL_OPS
#define ESP32_USING_WIFI_OPS
#define ESP32_USING_NETCONN_OPS
#define ESP32_USING_TCP
#define ESP32_USING_UDP
#define ESP32_USING_SELECT
#define ESP32_USING_DNS
#define ESP32_USING_ADDRINFO
#define ESP32_USING_SOCKETS_OPS

/* 4G Cat1 */

#define MOLINK_MULTI_USING_EC200X_600S

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_ML302

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_GM190

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_A7600X

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_A7670X

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_L610

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_AIR723UG

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_N58

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_CLM920RV3

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_AIR720UH

/* Config */

/* end of Config */
/* end of 4G Cat1 */

/* 4G Cat4 */

#define MOLINK_MULTI_USING_GM510

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_EC20

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_SIM7600CE

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_ME3630_W

/* Config */

/* end of Config */
/* end of 4G Cat4 */

/* NB-IOT */

#define MOLINK_MULTI_USING_M5310A

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_M5311

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_BC95

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_BC28

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_BC26

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_BC20

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_SIM7020

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_SIM7070X

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_N21

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_GM120

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_ME3616

/* Config */

/* end of Config */
/* end of NB-IOT */

/* WiFi */

#define MOLINK_MULTI_USING_ESP8266

/* Config */

/* end of Config */
#define MOLINK_MULTI_USING_ESP32

/* Config */

/* end of Config */
/* end of WiFi */
/* end of Modules */

/* Parser */

#define MOLINK_USING_PARSER
#define AT_PARSER_TASK_STACK_SIZE 512
/* end of Parser */
/* end of Molink */

/* OTA */

/* CMIOT Fota */

#define FOTA_USING_CMIOT
#define CMIOT_NETWORKING_MODE_COAP
#define CMIOT_DEFAULT_NETWORK_PROTOCOL 1
#define CMIOT_ALGORITHM_LUSUN
#define CMIOT_FOTA_ALGORITHM 0
#define CMIOT_DEFAULT_SECTOR_SIZE 0x800
#define CMIOT_FOTA_WOSUN_VERSION "IOT4.0_R42641"
#define CMIOT_FOTA_LUSUN_VERSION "IOT5.0_LUSUN11_R50426"
#define CMIOT_SEGMENT_SIZE_INDEX_START 0
#define CMIOT_DEFAULT_SEGMENT_SIZE_INDEX 3
#define CMIOT_FOTA_SERVICE_OEM "cmiot_cd"
#define CMIOT_FOTA_SERVICE_MODEL "L475RE"
#define CMIOT_FOTA_SERVICE_PRODUCT_ID "1571101950"
#define CMIOT_FOTA_SERVICE_PRODUCT_SEC "c36b6a45f78546e1a11390a90ee7f158"
#define CMIOT_FOTA_SERVICE_DEVICE_TYPE "box"
#define CMIOT_FOTA_SERVICE_PLATFORM "stm32l4"
#define CMIOT_FIRMWARE_VERSION "1.0"
#define CMIOT_FOTA_OS_VERSION "ONEOS_V1.0"
/* end of CMIOT Fota */
/* end of OTA */

/* Shell */

#define OS_USING_SHELL
#define SHELL_TASK_NAME "shell"
#define SHELL_TASK_PRIORITY 20
#define SHELL_TASK_STACK_SIZE 1024
#define SHELL_USING_DESCRIPTION
#define SHELL_CMD_SIZE 80
#define SHELL_PROMPT_SIZE 256
#define SHELL_ARG_MAX 10
/* end of Shell */

/* Socket */

#define NET_USING_BSD
#define BSD_USING_MOLINK
/* end of Socket */

/* Cplusplus */

/* end of Cplusplus */
/* end of Components */

/* Thirdparty */

/* Submodule */

#define OS_USING_SUBMODULE
/* end of Submodule */

/* PowerManager */

/* end of PowerManager */
/* end of Thirdparty */

#endif /* __ONEOS_CONFIG_H__ */

