from build_tools import *

pwd = PresentDir()
src = []

CPPPATH = [pwd + '/include']

if IsDefined("MOLINK_USING_EASYLOG"):
    src += Glob('source/mo_easylog.c')

group = AddCodeGroup('molink', src, depend = ['MOLINK_USING_EASYLOG'], CPPPATH = CPPPATH)

Return('group')
