from build_tools import *

pwd  = PresentDir()
CPPPATH = [pwd + '/include']
src = Glob('source/*.c') + Glob('source/*.cpp')
group = AddCodeGroup('cplusplus', src, depend = ['OS_USING_CPLUSPLUS'], CPPPATH = CPPPATH)

Return('group')
