#ifndef __ONEOS_CONFIG_H__
#define __ONEOS_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define BSP_USING_GPIO
#define BSP_USING_UART
#define BSP_USING_UART1
#define OS_USING_PIN
#define OS_USING_SERIAL
#define BOARD_ATK_ELITE
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M3

/* Kernel */

#define OS_CUSTOMIZED_CONFIG
#define OS_NAME_MAX 15
#define OS_TASK_PRIORITY_MAX 32
#define OS_MAIN_TASK_STACK_SIZE 2048
#define OS_IDLE_TASK_STACK_SIZE 512
#define OS_RECYCLE_TASK_STACK_SIZE 512
#define OS_USING_TIMER
#define OS_TIMER_TASK_STACK_SIZE 512
#define OS_USING_MUTEX
#define OS_USING_SEMAPHORE
#define OS_USING_SYS_HEAP
#define OS_USING_MEM_HEAP
#define OS_USING_ALG_SMALL
#define OS_MEM_ALGORITHM_MINIMIZATION
#define OS_DEBUG
#define EXCEPTION_SIMPLE_HANDLE
#define OS_TICK_PER_SECOND 100
#define OS_SCHEDULE_TIME_SLICE 10

/* Task */

#define OS_NAME_MAX_15
#define OS_TASK_PRIORITY_32
/* end of Task */

/* Timer */

/* end of Timer */

/* IPC */

/* end of IPC */

/* Memory */

/* algorithm */

/* end of algorithm */
/* end of Memory */

/* Debug */

#define OBJECT_INIT_REPEAT_CHECK
#define OS_USING_OVERFLOW_CHECK
/* end of Debug */
/* end of Kernel */

/* Drivers */

/* Device */

#define OS_USING_DEVICE
#define OS_DEVICE_NAME_MAX 15
/* end of Device */

/* Console */

#define OS_USING_CONSOLE
#define OS_CONSOLE_DEVICE_NAME "uart1"
#define OS_LOG_BUFF_SIZE 256
/* end of Console */

/* Serial */

#define OS_SERIAL_RX_BUFSZ 64
#define OS_SERIAL_TX_BUFSZ 64
/* end of Serial */

/* Timer */

#define OS_USING_TIMER_DRIVER
#define OS_USING_CLOCKSOURCE

/* cortex-m hardware timer config */

#define OS_USING_SYSTICK_FOR_KERNEL_TICK
/* end of cortex-m hardware timer config */
/* end of Timer */

/* LPMGR */

/* end of LPMGR */
#define OS_USING_PUSH_BUTTON
#define OS_USING_LED

/* ADC */

/* end of ADC */
#define OS_PIN_MAX_CHIP 1

/* HAL */

#define MANUFACTOR_STM32
#define SERIES_STM32F1
#define SOC_STM32F103xE
#define BSP_BOOT_OPTION
#define BSP_TEXT_SECTION_ADDR 0x08000000
#define BSP_TEXT_SECTION_SIZE 0x00020000
#define BSP_DATA_SECTION_ADDR 0x20000000
#define BSP_DATA_SECTION_SIZE 0x00005000

/* Configure base hal in STM32CubeMX */

/* end of HAL */
/* end of Drivers */

/* Components */

/* Atest */

/* end of Atest */
#define OS_USING_NEWLIB_ADAPTER
#define OS_USING_ARMCCLIB_ADAPTER
#define OS_USING_LIBC_ADAPTER

/* Molink */

/* end of Molink */

/* OTA */

/* CMIOT Fota */

/* end of CMIOT Fota */
/* end of OTA */

/* Shell */

#define OS_USING_SHELL
#define SHELL_TASK_NAME "shell"
#define SHELL_TASK_PRIORITY 20
#define SHELL_TASK_STACK_SIZE 2048
#define SHELL_USING_DESCRIPTION
#define SHELL_CMD_SIZE 80
#define SHELL_PROMPT_SIZE 256
#define SHELL_ARG_MAX 10
/* end of Shell */

/* Socket */

/* end of Socket */
/* end of Components */

#endif /* __ONEOS_CONFIG_H__ */

