#ifndef __ONEOS_CONFIG_H__
#define __ONEOS_CONFIG_H__

/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define BOARD_STM32F407XX
#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M4

/* Kernel */

#define OS_CUSTOMIZED_CONFIG
#define OS_NAME_MAX 15
#define OS_TASK_PRIORITY_MAX 32
#define OS_MAIN_TASK_STACK_SIZE 4096
#define OS_IDLE_TASK_STACK_SIZE 2048
#define OS_RECYCLE_TASK_STACK_SIZE 1024
#define OS_USING_MUTEX
#define OS_USING_SEMAPHORE
#define OS_USING_EVENT
#define OS_USING_MESSAGEQUEUE
#define OS_USING_MAILBOX
#define OS_USING_SYS_HEAP
#define OS_USING_MEM_HEAP
#define OS_USING_ALG_SMALL
#define OS_MEM_ALGORITHM_MINIMIZATION
#define OS_DEBUG
#define EXCEPTION_SIMPLE_HANDLE
#define OS_TICK_PER_SECOND 10
#define OS_SCHEDULE_TIME_SLICE 10

/* Task */

#define OS_NAME_MAX_15
#define OS_TASK_PRIORITY_32
/* end of Task */

/* Timer */

/* end of Timer */

/* IPC */

/* end of IPC */

/* Memory */

/* algorithm */

#define OS_USING_ALG_FIRSTFIT
/* end of algorithm */
#define OS_USING_MEM_POOL
/* end of Memory */

/* Debug */

#define OS_USING_ASSERT
#define OS_USING_KERNEL_LOCK_CHECK
#define OS_USING_KERNEL_DEBUG
#define KLOG_GLOBAL_LEVEL_WARNING
#define KLOG_GLOBAL_LEVEL 1
#define KLOG_USING_COLOR
#define KLOG_WITH_FUNC_LINE
#define OS_USING_OVERFLOW_CHECK
/* end of Debug */
/* end of Kernel */

/* Drivers */

/* Device */

#define OS_USING_DEVICE
#define OS_DEVICE_NAME_MAX 15
/* end of Device */

/* Console */

#define OS_USING_CONSOLE
#define OS_CONSOLE_DEVICE_NAME "uart1"
#define OS_LOG_BUFF_SIZE 256
/* end of Console */

/* Serial */

#define OS_USING_SERIAL
#define OS_SERIAL_RX_BUFSZ 1
#define OS_SERIAL_TX_BUFSZ 64
/* end of Serial */

/* Timer */

#define OS_USING_TIMER_DRIVER
#define OS_USING_CLOCKSOURCE

/* cortex-m hardware timer config */

#define OS_USING_SYSTICK_FOR_KERNEL_TICK
/* end of cortex-m hardware timer config */
/* end of Timer */

/* LPMGR */

/* end of LPMGR */
#define OS_USING_PUSH_BUTTON
#define OS_USING_LED

/* ADC */

/* end of ADC */
#define OS_USING_PIN
#define OS_PIN_MAX_CHIP 1

/* HAL */

#define MANUFACTOR_STM32
#define SERIES_STM32F4
#define SOC_STM32F4XX
#define BSP_BOOT_OPTION
#define BSP_TEXT_SECTION_ADDR 0x08000000
#define BSP_TEXT_SECTION_SIZE 0x00100000
#define BSP_DATA_SECTION_ADDR 0x20000000
#define BSP_DATA_SECTION_SIZE 0x00020000

/* Configure base hal in STM32CubeMX */

/* end of HAL */

/* RTC */

/* end of RTC */
/* end of Drivers */

/* Components */

/* Atest */

/* end of Atest */

/* Dlog */

/* end of Dlog */
#define OS_USING_NEWLIB_ADAPTER
#define OS_USING_ARMCCLIB_ADAPTER
#define OS_USING_LIBC_ADAPTER

/* Molink */

/* end of Molink */

/* OTA */

/* CMIOT Fota */

/* end of CMIOT Fota */
/* end of OTA */

/* Shell */

#define OS_USING_SHELL
#define SHELL_TASK_NAME "shell"
#define SHELL_TASK_PRIORITY 20
#define SHELL_TASK_STACK_SIZE 1024
#define SHELL_USING_DESCRIPTION
#define SHELL_CMD_SIZE 80
#define SHELL_PROMPT_SIZE 256
#define SHELL_ARG_MAX 10
/* end of Shell */

/* Socket */

/* end of Socket */

/* Cplusplus */

/* end of Cplusplus */
/* end of Components */

/* Thirdparty */

/* Submodule */

#define OS_USING_SUBMODULE
/* end of Submodule */

/* PowerManager */

/* end of PowerManager */
/* end of Thirdparty */

#endif /* __ONEOS_CONFIG_H__ */

