Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
drv_common.c
""")

path = [pwd]

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32L13']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32L17']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32L19']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32L07']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32F07']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32F17']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_ON_CHIP_FLASH', 'SERIES_HC32F19']):
    src += ['flash/drv_flash.c']

if IsDefined(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

if IsDefined(['OS_USING_I2C']):
    src += ['drv_i2c.c']

if IsDefined(['OS_USING_DAC']):
    src += ['drv_dac.c']

if IsDefined(['OS_USING_ADC']):
    src += ['drv_adc.c']

if IsDefined(['OS_USING_SPI', 'BSP_USING_SPI0']) or IsDefined(['OS_USING_SPI', 'BSP_USING_SPI1']):
    src += ['drv_spi.c']

if IsDefined(['OS_USING_TIMER_DRIVER']):
    src += ['drv_hwtimer.c']

if IsDefined(['OS_USING_CLOCKEVENT']):
    src += ['drv_lptim.c']

if IsDefined(['OS_USING_TICKLESS_LPMGR']):
    src += ['drv_lpmgr.c']

if IsDefined(['OS_USING_SIMPLE_LPM']):
    src += ['drv_lpm.c']

if IsDefined(['BSP_USING_UART', 'SERIES_HC32L13']):
    src += ['drv_usart.c']

if IsDefined(['BSP_USING_UART', 'SERIES_HC32L17']) or IsDefined(['BSP_USING_UART', 'SERIES_HC32L19']) or IsDefined(['BSP_USING_UART', 'SERIES_HC32L07']):
    src += ['drv_usart.c']

if IsDefined(['BSP_USING_UART', 'SERIES_HC32F07']):
    src += ['drv_usart.c']

if IsDefined(['BSP_USING_UART', 'SERIES_HC32F17']):
    src += ['drv_usart.c']

if IsDefined(['BSP_USING_UART', 'SERIES_HC32F19']):
    src += ['drv_usart.c']

if IsDefined(['OS_USING_WDG']):
    src += ['drv_wdg.c']

if IsDefined(['OS_USING_RTC']):
    src += ['drv_rtc.c']

path = [pwd]

CPPDEFINES = ['USE_HAL_DRIVER']
group = AddCodeGroup('hal/drivers', src, depend = ['MANUFACTOR_HC32'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
