Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_PIN']):
    src += ['drv_gpio.c']

if IsDefined(['OS_USING_SERIAL']):
    src += ['drv_uart.c']
    
path =  [pwd]
group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_MM32L3XX'], CPPPATH = path)

Return('group')
