Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
drv_common.c
mm32_it.c
mm32_it_dma.c
""")
    
path =  [pwd]
group = AddCodeGroup('hal/drivers', src, depend = ['MANUFACTOR_MM32'], CPPPATH = path)

Return('group')
